all_packages = {"Aircrack-ng": "scripts/Aircrack-ng.sh",
                "Amap": "scripts/Amap.sh",
                "Arduino": "scripts/Arduino.sh",
                "Armitage": "scripts/Armitage.sh",
                "Asleap": "scripts/Asleap.sh",
                "Automater": "scripts/Automater.sh",
                "BBQSQL": "scripts/BBQSQL.sh",
                "BED": "scripts/BED.sh",
                "Backdoor Factory": "scripts/Backdoor_Factory.sh",
                "BeEF": "scripts/BeEF.sh",
                "Binwalk": "scripts/Binwalk.sh",
                "BlueMaho": "scripts/BlueMaho.sh",
                "BlueRanger": "scripts/BlueRanger.sh",
                "Bluelog": "scripts/Bluelog.sh",
                "Bluepot": "scripts/Bluepot.sh",
                "Bluesnarfer": "scripts/Bluesnarfer.sh",
                "Bully": "scripts/Bully.sh",
                "Burp Suite": "scripts/Burp_Suite.sh",
                "CDPSnarf": "scripts/CDPSnarf.sh",
                "Capstone": "scripts/Capstone.sh",
                "CaseFile": "scripts/CaseFile.sh",
                "CeWL": "scripts/CeWL.sh",
                "CmosPwd": "scripts/CmosPwd.sh",
                "Commix": "scripts/Commix.sh",
                "Cookie Cadger": "scripts/Cookie_Cadger.sh",
                "CryptCat": "scripts/CryptCat.sh",
                "Cuckoo": "scripts/Cuckoo.sh",
                "CutyCapt": "scripts/CutyCapt.sh",
                "Cymothoa": "scripts/Cymothoa.sh",
                "DBPwAudit": "scripts/DBPwAudit.sh",
                "DFF": "scripts/DFF.sh",
                "DHCPig": "scripts/DHCPig.sh",
                "DMitry": "scripts/DMitry.sh",
                "DNSChef": "scripts/DNSChef.sh",
                "DNSRecon": "scripts/DNSRecon.sh",
                "Doona": "scripts/Doona.sh",
                "DotDotPwn": "scripts/DotDotPwn.sh",
                "Dradis": "scripts/Dradis.sh",
                "Dumpzilla": "scripts/Dumpzilla.sh",
                "Fern Wifi Cracker": "scripts/Fern_Wifi_Cracker.sh",
                "Fierce": "scripts/Fierce.sh",
                "Firewalk": "scripts/Firewalk.sh",
                "Foremost": "scripts/Foremost.sh",
                "FunkLoad": "scripts/FunkLoad.sh",
                "GISKismet": "scripts/GISKismet.sh",
                "GSD": "scripts/GSD.sh",
                "Galleta": "scripts/Galleta.sh",
                "Ghost Phisher": "scripts/Ghost_Phisher.sh",
                "GoLismero": "scripts/GoLismero.sh",
                "Gqrx": "scripts/Gqrx.sh",
                "Greenbone Security Assistant": "scripts/Greenbone_Security_Assistant.sh",
                "Guymager": "scripts/Guymager.sh",
                "HTTPTunnel": "scripts/HTTPTunnel.sh",
                "HexInject": "scripts/HexInject.sh",
                "HexorBase": "scripts/HexorBase.sh",
                "InTrace": "scripts/InTrace.sh",
                "Inguma": "scripts/Inguma.sh",
                "Intersect": "scripts/Intersect.sh",
                "Inundator": "scripts/Inundator.sh",
                "JD-GUI": "scripts/JD-GUI.sh",
                "John the Ripper": "scripts/John_the_Ripper.sh",
                "Johnny": "scripts/Johnny.sh",
                "KeepNote": "scripts/KeepNote.sh",
                "KillerBee": "scripts/KillerBee.sh",
                "Kismet": "scripts/Kismet.sh",
                "Linux Exploit Suggester": "scripts/Linux_Exploit_Suggester.sh",
                "Lynis": "scripts/Lynis.sh",
                "MagicTree": "scripts/MagicTree.sh",
                "Maltego Teeth": "scripts/Maltego_Teeth.sh",
                "Maskprocessor": "scripts/Maskprocessor.sh",
                "Metagoofil": "scripts/Metagoofil.sh",
                "Miranda": "scripts/Miranda.sh",
                "Multimon-NG": "scripts/Multimon-NG.sh",
                "Ncrack": "scripts/Ncrack.sh",
                "Nipper-ng": "scripts/Nipper-ng.sh",
                "Nishang": "scripts/Nishang.sh",
                "Nmap": "scripts/Nmap.sh",
                "OllyDbg": "scripts/OllyDbg.sh",
                "Oscanner": "scripts/Oscanner.sh",
                "PACK": "scripts/PACK.sh",
                "Parsero": "scripts/Parsero.sh",
                "PixieWPS": "scripts/PixieWPS.sh",
                "PowerSploit": "scripts/PowerSploit.sh",
                "Powerfuzzer": "scripts/Powerfuzzer.sh",
                "RSMangler": "scripts/RSMangler.sh",
                "RTLSDR Scanner": "scripts/RTLSDR_Scanner.sh",
                "RainbowCrack": "scripts/RainbowCrack.sh",
                "Reaver": "scripts/Reaver.sh",
                "Recon-ng": "scripts/Recon-ng.sh",
                "RegRipper": "scripts/RegRipper.sh",
                "RidEnum": "scripts/RidEnum.sh",
                "SET": "scripts/SET.sh",
                "SIPArmyKnife": "scripts/SIPArmyKnife.sh",
                "SIPVicious": "scripts/SIPVicious.sh",
                "SIPp": "scripts/SIPp.sh",
                "SQLdict": "scripts/SQLdict.sh",
                "SSLsplit": "scripts/SSLsplit.sh",
                "SSLyze": "scripts/SSLyze.sh",
                "Sakis3G": "scripts/Sakis3G.sh",
                "ShellNoob": "scripts/ShellNoob.sh",
                "SidGuesser": "scripts/SidGuesser.sh",
                "SlowHTTPTest": "scripts/SlowHTTPTest.sh",
                "SniffJoke": "scripts/SniffJoke.sh",
                "Spooftooph": "scripts/Spooftooph.sh",
                "Sqlninja": "scripts/Sqlninja.sh",
                "Statsprocessor": "scripts/Statsprocessor.sh",
                "THC-Hydra": "scripts/THC-Hydra.sh",
                "THC-IPV6": "scripts/THC-IPV6.sh",
                "THC-SSL-DOS": "scripts/THC-SSL-DOS.sh",
                "THC-pptp-bruter": "scripts/THC-pptp-bruter.sh",
                "TLSSLed": "scripts/TLSSLed.sh",
                "Termineter": "scripts/Termineter.sh",
                "TrueCrack": "scripts/TrueCrack.sh",
                "U3-Pwn": "scripts/U3-Pwn.sh",
                "URLCrazy": "scripts/URLCrazy.sh",
                "Valgrind": "scripts/Valgrind.sh",
                "VoIPHopper": "scripts/VoIPHopper.sh",
                "Volatility": "scripts/Volatility.sh",
                "WOL-E": "scripts/WOL-E.sh",
                "WebScarab": "scripts/WebScarab.sh",
                "Webshells": "scripts/Webshells.sh",
                "Weevely": "scripts/Weevely.sh",
                "Wifi Honey": "scripts/Wifi_Honey.sh",
                "Wifitap": "scripts/Wifitap.sh",
                "Wifite": "scripts/Wifite.sh",
                "Winexe": "scripts/Winexe.sh",
                "Wireshark": "scripts/Wireshark.sh",
                "Xplico": "scripts/Xplico.sh",
                "YARA": "scripts/YARA.sh",
                "Yersinia": "scripts/Yersinia.sh",
                "acccheck": "scripts/acccheck.sh",
                "ace-voip": "scripts/ace-voip.sh",
                "android-sdk": "scripts/android-sdk.sh",
                "apktool": "scripts/apktool.sh",
                "bing-ip2hosts": "scripts/bing-ip2hosts.sh",
                "braa": "scripts/braa.sh",
                "bulk-extractor": "scripts/bulk-extractor.sh",
                "chntpw": "scripts/chntpw.sh",
                "cisco-auditing-tool": "scripts/cisco-auditing-tool.sh",
                "cisco-global-exploiter": "scripts/cisco-global-exploiter.sh",
                "cisco-ocs": "scripts/cisco-ocs.sh",
                "cisco-torch": "scripts/cisco-torch.sh",
                "coWPAtty": "scripts/coWPAtty.sh",
                "copy-router-config": "scripts/copy-router-config.sh",
                "crackle": "scripts/crackle.sh",
                "creddump": "scripts/creddump.sh",
                "crunch": "scripts/crunch.sh",
                "dbd": "scripts/dbd.sh",
                "dc3dd": "scripts/dc3dd.sh",
                "ddrescue": "scripts/ddrescue.sh",
                "dex2jar": "scripts/dex2jar.sh",
                "diStorm3": "scripts/diStorm3.sh",
                "dnmap": "scripts/dnmap.sh",
                "dns2tcp": "scripts/dns2tcp.sh",
                "dnsenum": "scripts/dnsenum.sh",
                "dnsmap": "scripts/dnsmap.sh",
                "dnstracer": "scripts/dnstracer.sh",
                "dnswalk": "scripts/dnswalk.sh",
                "dos2unix": "scripts/dos2unix.sh",
                "eapmd5pass": "scripts/eapmd5pass.sh",
                "edb-debugger": "scripts/edb-debugger.sh",
                "enum4linux": "scripts/enum4linux.sh",
                "enumIAX": "scripts/enumIAX.sh",
                "exploitdb": "scripts/exploitdb.sh",
                "extundelete": "scripts/extundelete.sh",
                "fiked": "scripts/fiked.sh",
                "findmyhash": "scripts/findmyhash.sh",
                "fragroute": "scripts/fragroute.sh",
                "fragrouter": "scripts/fragrouter.sh",
                "goofile": "scripts/goofile.sh",
                "gpp-decrypt": "scripts/gpp-decrypt.sh",
                "gr-scan": "scripts/gr-scan.sh",
                "hamster-sidejack": "scripts/hamster-sidejack.sh",
                "hash-identifier": "scripts/hash-identifier.sh",
                "hping3": "scripts/hping3.sh",
                "http-tunnel": "scripts/http-tunnel.sh",
                "iPhone Backup Analyzer": "scripts/iPhone_Backup_Analyzer.sh",
                "iSMTP": "scripts/iSMTP.sh",
                "iaxflood": "scripts/iaxflood.sh",
                "inviteflood": "scripts/inviteflood.sh",
                "ipv6-toolkit": "scripts/ipv6-toolkit.sh",
                "isr-evilgrade": "scripts/isr-evilgrade.sh",
                "jSQL": "scripts/jSQL.sh",
                "jad": "scripts/jad.sh",
                "javasnoop": "scripts/javasnoop.sh",
                "jboss-autopwn": "scripts/jboss-autopwn.sh",
                "kalibrate-rtl": "scripts/kalibrate-rtl.sh",
                "keimpx": "scripts/keimpx.sh",
                "lbd": "scripts/lbd.sh",
                "masscan": "scripts/masscan.sh",
                "mdk3": "scripts/mdk3.sh",
                "mfcuk": "scripts/mfcuk.sh",
                "mfoc": "scripts/mfoc.sh",
                "mfterm": "scripts/mfterm.sh",
                "mitmproxy": "scripts/mitmproxy.sh",
                "multiforcer": "scripts/multiforcer.sh",
                "ntop": "scripts/ntop.sh",
                "oclgausscrack": "scripts/oclgausscrack.sh",
                "ohrwurm": "scripts/ohrwurm.sh",
                "openvas-administrator": "scripts/openvas-administrator.sh",
                "openvas-cli": "scripts/openvas-cli.sh",
                "openvas-manager": "scripts/openvas-manager.sh",
                "openvas-scanner": "scripts/openvas-scanner.sh",
                "p0f": "scripts/p0f.sh",
                "patator": "scripts/patator.sh",
                "pdf-parser": "scripts/pdf-parser.sh",
                "pdfid": "scripts/pdfid.sh",
                "pdgmail": "scripts/pdgmail.sh",
                "peepdf": "scripts/peepdf.sh",
                "phrasendrescher": "scripts/phrasendrescher.sh",
                "pipal": "scripts/pipal.sh",
                "polenum": "scripts/polenum.sh",
                "protos-sip": "scripts/protos-sip.sh",
                "pwnat": "scripts/pwnat.sh",
                "rcracki-mt": "scripts/rcracki-mt.sh",
                "rebind": "scripts/rebind.sh",
                "redfang": "scripts/redfang.sh",
                "responder": "scripts/responder.sh",
                "rtpbreak": "scripts/rtpbreak.sh",
                "rtpflood": "scripts/rtpflood.sh",
                "rtpinsertsound": "scripts/rtpinsertsound.sh",
                "rtpmixsound": "scripts/rtpmixsound.sh",
                "sbd": "scripts/sbd.sh",
                "sctpscan": "scripts/sctpscan.sh",
                "sfuzz": "scripts/sfuzz.sh",
                "smali": "scripts/smali.sh",
                "smtp-user-enum": "scripts/smtp-user-enum.sh",
                "snmpcheck": "scripts/snmpcheck.sh",
                "sqlmap": "scripts/sqlmap.sh",
                "sqlsus": "scripts/sqlsus.sh",
                "sslcaudit": "scripts/sslcaudit.sh",
                "sslstrip": "scripts/sslstrip.sh",
                "t50": "scripts/t50.sh",
                "theHarvester": "scripts/theHarvester.sh",
                "tnscmd10g": "scripts/tnscmd10g.sh",
                "twofi": "scripts/twofi.sh",
                "unix-privesc-check": "scripts/unix-privesc-check.sh",
                "wordlists": "scripts/wordlists.sh",
                "xspy": "scripts/xspy.sh",
                "zaproxy": "scripts/zaproxy.sh"}

info = {"1": "acccheck", "2": "ace-voip", "3": "Amap", "4": "Automater",
        "5": "bing-ip2hosts", "6": "braa", "7": "CaseFile", "8": "CDPSnarf",
        "9": "cisco-torch", "10": "Cookie Cadger", "11": "copy-router-config",
        "12": "DMitry", "13": "dnmap", "14": "dnsenum", "15": "dnsmap",
        "16": "DNSRecon", "17": "dnstracer", "18": "dnswalk",
        "19": "DotDotPwn", "20": "enum4linux", "21": "enumIAX",
        "22": "exploitdb", "23": "Fierce", "24": "Firewalk", "25": "fragroute",
        "26": "fragrouter", "27": "Ghost Phisher", "28": "GoLismero",
        "29": "goofile", "30": "hping3", "31": "InTrace", "32": "iSMTP",
        "33": "lbd", "34": "Maltego Teeth", "35": "masscan",
        "36": "Metagoofil", "37": "Miranda", "38": "Nmap", "39": "ntop",
        "40": "p0f", "41": "Parsero", "42": "Recon-ng", "43": "SET",
        "44": "smtp-user-enum", "45": "snmpcheck", "46": "sslcaudit",
        "47": "SSLsplit", "48": "sslstrip", "49": "SSLyze", "50": "THC-IPV6",
        "51": "theHarvester", "52": "TLSSLed", "53": "twofi", "54": "URLCrazy",
        "55": "Wireshark", "56": "WOL-E", "57": "Xplico"}


vulnerability = {"1": "BBQSQL", "2": "BED", "3": "cisco-auditing-tool",
                 "4": "cisco-global-exploiter", "5": "cisco-ocs",
                 "6": "cisco-torch", "7": "copy-router-config",
                 "8": "DBPwAudit", "9": "Doona", "10": "DotDotPwn",
                 "11": "Greenbone Security Assistant", "12": "GSD",
                 "13": "HexorBase", "14": "Inguma", "15": "jSQL",
                 "16": "Lynis", "17": "Nmap", "18": "ohrwurm",
                 "19": "openvas-administrator", "20": "openvas-cli",
                 "21": "openvas-manager", "22": "openvas-scanner",
                 "23": "Oscanner", "24": "Powerfuzzer", "25": "sfuzz",
                 "26": "SidGuesser", "27": "SIPArmyKnife",
                 "28": "sqlmap", "29": "Sqlninja", "30": "sqlsus",
                 "31": "THC-IPV6", "32": "tnscmd10g",
                 "33": "unix-privesc-check", "34": "Yersinia"}

wifi = {"1": "Aircrack-ng", "2": "Asleap", "3": "Bluelog", "4": "BlueMaho",
        "5": "Bluepot", "6": "BlueRanger", "7": "Bluesnarfer", "8": "Bully",
        "9": "coWPAtty", "10": "crackle", "11": "eapmd5pass",
        "12": "Fern Wifi Cracker", "13": "Ghost Phisher", "14": "GISKismet",
        "15": "Gqrx", "16": "gr-scan", "17": "kalibrate-rtl",
        "18": "KillerBee", "19": "Kismet", "20": "mdk3", "21": "mfcuk",
        "22": "mfoc", "23": "mfterm", "24": "Multimon-NG", "25": "PixieWPS",
        "26": "Reaver", "27": "redfang", "28": "RTLSDR Scanner",
        "29": "Spooftooph", "30": "Wifi Honey", "31": "Wifitap",
        "32": "Wifite"}

sniff_n_spoof = {"1": "Burp Suite", "2": "DNSChef", "3": "fiked",
                 "4": "hamster-sidejack", "5": "HexInject", "6": "iaxflood",
                 "7": "inviteflood", "8": "iSMTP", "9": "isr-evilgrade",
                 "10": "mitmproxy", "11": "ohrwurm", "12": "protos-sip",
                 "13": "rebind", "14": "responder", "15": "rtpbreak",
                 "16": "rtpinsertsound", "17": "rtpmixsound", "18": "sctpscan",
                 "19": "SIPArmyKnife", "20": "SIPp", "21": "SIPVicious",
                 "22": "SniffJoke", "23": "SSLsplit", "24": "sslstrip",
                 "25": "THC-IPV6", "26": "VoIPHopper", "27": "WebScarab",
                 "28": "Wifi Honey", "29": "Wireshark", "30": "xspy",
                 "31": "Yersinia", "32": "zaproxy"}

access = {"1": "CryptCat", "2": "Cymothoa", "3": "dbd", "4": "dns2tcp",
          "5": "http-tunnel", "6": "HTTPTunnel", "7": "Intersect",
          "8": "Nishang", "9": "polenum", "10": "PowerSploit", "11": "pwnat",
          "12": "RidEnum", "13": "sbd", "14": "U3-Pwn", "15": "Webshells",
          "16": "Weevely", "17": "Winexe"}

report = {"1": "CaseFile", "2": "CutyCapt", "3": "dos2unix", "4": "Dradis",
          "5": "KeepNote", "6": "MagicTree", "7": "Metagoofil",
          "8": "Nipper-ng", "9": "pipal"}

exploit = {"1": "Armitage", "2": "Backdoor Factory", "3": "BeEF",
           "4": "cisco-auditing-tool", "5": "cisco-global-exploiter",
           "6": "cisco-ocs", "7": "cisco-torch", "8": "Commix", "9": "crackle",
           "10": "jboss-autopwn", "11": "Linux Exploit Suggester",
           "12": "Maltego Teeth", "13": "SET", "14": "ShellNoob",
           "15": "sqlmap", "16": "THC-IPV6", "17": "Yersinia"}

forensics = {"1": "Binwalk", "2": "bulk-extractor", "3": "Capstone",
             "4": "chntpw", "5": "Cuckoo", "6": "dc3dd", "7": "ddrescue",
             "8": "DFF", "9": "diStorm3", "10": "Dumpzilla",
             "11": "extundelete", "12": "Foremost", "13": "Galleta",
             "14": "Guymager", "15": "iPhone Backup Analyzer", "16": "p0f",
             "17": "pdf-parser", "18": "pdfid", "19": "pdgmail",
             "20": "peepdf", "21": "RegRipper", "22": "Volatility",
             "23": "Xplico"}

stress_test = {"1": "DHCPig", "2": "FunkLoad", "3": "iaxflood",
               "4": "Inundator", "5": "inviteflood", "6": "ipv6-toolkit",
               "7": "mdk3", "8": "Reaver", "9": "rtpflood",
               "10": "SlowHTTPTest", "11": "t50", "12": "Termineter",
               "13": "THC-IPV6", "14": "THC-SSL-DOS"}

password = {"1": "acccheck", "2": "Burp Suite", "3": "CeWL", "4": "chntpw",
            "5": "cisco-auditing-tool", "6": "CmosPwd", "7": "creddump",
            "8": "crunch", "9": "DBPwAudit", "10": "findmyhash",
            "11": "gpp-decrypt", "12": "hash-identifier", "13": "HexorBase",
            "14": "THC-Hydra", "15": "John the Ripper", "16": "Johnny",
            "17": "keimpx", "18": "Maltego Teeth", "19": "Maskprocessor",
            "20": "multiforcer", "21": "Ncrack", "22": "oclgausscrack",
            "23": "PACK", "24": "patator", "25": "phrasendrescher",
            "26": "polenum", "27": "RainbowCrack", "28": "rcracki-mt",
            "29": "RSMangler", "30": "SQLdict", "31": "Statsprocessor",
            "32": "THC-pptp-bruter", "33": "TrueCrack", "34": "WebScarab",
            "35": "wordlists", "36": "zaproxy"}

rev_engineer = {"1": "apktool", "2": "dex2jar", "3": "diStorm3",
                "4": "edb-debugger", "5": "jad", "6": "javasnoop",
                "7": "JD-GUI", "8": "OllyDbg", "9": "smali",
                "10": "Valgrind", "11": "YARA"}

hw_hacking = {"1": "android-sdk", "2": "apktool", "3": "Arduino",
              "4": "dex2jar", "5": "Sakis3G", "6": "smali"}


categories = [info, vulnerability, wifi, sniff_n_spoof, access, report,
              exploit, forensics, stress_test, password, rev_engineer,
              hw_hacking]
