all_packages = {"Aircrack-ng": "scripts/Aircrack-ng.sh",
                "Amap": "scripts/Amap.sh",
                "Arachni": "scripts/Arachni.sh",
                "Arduino": "scripts/Arduino.sh",
                "Armitage": "scripts/Armitage.sh",
                "Asleap": "scripts/Asleap.sh",
                "Automater": "scripts/Automater.sh",
                "BBQSQL": "scripts/BBQSQL.sh",
                "BED": "scripts/BED.sh",
                "Backdoor Factory": "scripts/Backdoor_Factory.sh",
                "BeEF": "scripts/BeEF.sh",
                "Binwalk": "scripts/Binwalk.sh",
                "BlindElephant": "scripts/BlindElephant.sh",
                "BlueRanger": "scripts/BlueRanger.sh",
                "Bluelog": "scripts/Bluelog.sh",
                "Bluesnarfer": "scripts/Bluesnarfer.sh",
                "Bully": "scripts/Bully.sh",
                "Burp Suite": "scripts/Burp_Suite.sh",
                "CDPSnarf": "scripts/CDPSnarf.sh",
                "CaseFile": "scripts/CaseFile.sh",
                "CeWL": "scripts/CeWL.sh",
                "CmosPwd": "scripts/CmosPwd.sh",
                "Commix": "scripts/Commix.sh",
                "Cookie Cadger": "scripts/Cookie_Cadger.sh",
                "CryptCat": "scripts/CryptCat.sh",
                "Cuckoo": "scripts/Cuckoo.sh",
                "CutyCapt": "scripts/CutyCapt.sh",
                "Cymothoa": "scripts/Cymothoa.sh",
                "DAVTest": "scripts/DAVTest.sh",
                "DBPwAudit": "scripts/DBPwAudit.sh",
                "DHCPig": "scripts/DHCPig.sh",
                "DIRB": "scripts/DIRB.sh",
                "DMitry": "scripts/DMitry.sh",
                "DNSChef": "scripts/DNSChef.sh",
                "DNSRecon": "scripts/DNSRecon.sh",
                "DirBuster": "scripts/DirBuster.sh",
                "Doona": "scripts/Doona.sh",
                "DotDotPwn": "scripts/DotDotPwn.sh",
                "Dradis": "scripts/Dradis.sh",
                "Dumpzilla": "scripts/Dumpzilla.sh",
                "Fern Wifi Cracker": "scripts/Fern_Wifi_Cracker.sh",
                "Fierce": "scripts/Fierce.sh",
                "Firewalk": "scripts/Firewalk.sh",
                "Foremost": "scripts/Foremost.sh",
                "FunkLoad": "scripts/FunkLoad.sh",
                "GISKismet": "scripts/GISKismet.sh",
                "Galleta": "scripts/Galleta.sh",
                "Ghost Phisher": "scripts/Ghost_Phisher.sh",
                "GoLismero": "scripts/GoLismero.sh",
                "Gqrx": "scripts/Gqrx.sh",
                "Grabber": "scripts/Grabber.sh",
                "Greenbone Security Assistant": "scripts/Greenbone_Security_Assistant.sh",
                "Guymager": "scripts/Guymager.sh",
                "HTTPTunnel": "scripts/HTTPTunnel.sh",
                "HexInject": "scripts/HexInject.sh",
                "HexorBase": "scripts/HexorBase.sh",
                "InTrace": "scripts/InTrace.sh",
                "Inguma": "scripts/Inguma.sh",
                "Intersect": "scripts/Intersect.sh",
                "John the Ripper": "scripts/John_the_Ripper.sh",
                "Johnny": "scripts/Johnny.sh",
                "KeepNote": "scripts/KeepNote.sh",
                "KillerBee": "scripts/KillerBee.sh",
                "Kismet": "scripts/Kismet.sh",
                "Linux Exploit Suggester": "scripts/Linux_Exploit_Suggester.sh",
                "Lynis": "scripts/Lynis.sh",
                "MagicTree": "scripts/MagicTree.sh",
                "Maltego Teeth": "scripts/Maltego_Teeth.sh",
                "Maskprocessor": "scripts/Maskprocessor.sh",
                "Metagoofil": "scripts/Metagoofil.sh",
                "Miranda": "scripts/Miranda.sh",
                "Multimon-NG": "scripts/Multimon-NG.sh",
                "Ncrack": "scripts/Ncrack.sh",
                "Nipper-ng": "scripts/Nipper-ng.sh",
                "Nishang": "scripts/Nishang.sh",
                "Nmap": "scripts/Nmap.sh",
                "Oscanner": "scripts/Oscanner.sh",
                "PACK": "scripts/PACK.sh",
                "PadBuster": "scripts/PadBuster.sh",
                "Paros": "scripts/Paros.sh",
                "Parsero": "scripts/Parsero.sh",
                "PixieWPS": "scripts/PixieWPS.sh",
                "PowerSploit": "scripts/PowerSploit.sh",
                "Powerfuzzer": "scripts/Powerfuzzer.sh",
                "ProxyStrike": "scripts/ProxyStrike.sh",
                "RSMangler": "scripts/RSMangler.sh",
                "RTLSDR Scanner": "scripts/RTLSDR_Scanner.sh",
                "RainbowCrack": "scripts/RainbowCrack.sh",
                "Reaver": "scripts/Reaver.sh",
                "Recon-ng": "scripts/Recon-ng.sh",
                "RidEnum": "scripts/RidEnum.sh",
                "SET": "scripts/SET.sh",
                "SIPArmyKnife": "scripts/SIPArmyKnife.sh",
                "SIPVicious": "scripts/SIPVicious.sh",
                "SIPp": "scripts/SIPp.sh",
                "SSLsplit": "scripts/SSLsplit.sh",
                "SSLyze": "scripts/SSLyze.sh",
                "Sakis3G": "scripts/Sakis3G.sh",
                "ShellNoob": "scripts/ShellNoob.sh",
                "SidGuesser": "scripts/SidGuesser.sh",
                "Skipfish": "scripts/Skipfish.sh",
                "SlowHTTPTest": "scripts/SlowHTTPTest.sh",
                "Spooftooph": "scripts/Spooftooph.sh",
                "Sqlninja": "scripts/Sqlninja.sh",
                "Statsprocessor": "scripts/Statsprocessor.sh",
                "THC-Hydra": "scripts/THC-Hydra.sh",
                "THC-IPV6": "scripts/THC-IPV6.sh",
                "THC-SSL-DOS": "scripts/THC-SSL-DOS.sh",
                "THC-pptp-bruter": "scripts/THC-pptp-bruter.sh",
                "TLSSLed": "scripts/TLSSLed.sh",
                "Termineter": "scripts/Termineter.sh",
                "TrueCrack": "scripts/TrueCrack.sh",
                "U3-Pwn": "scripts/U3-Pwn.sh",
                "URLCrazy": "scripts/URLCrazy.sh",
                "Uniscan": "scripts/Uniscan.sh",
                "Valgrind": "scripts/Valgrind.sh",
                "Vega": "scripts/Vega.sh",
                "VoIPHopper": "scripts/VoIPHopper.sh",
                "Volatility": "scripts/Volatility.sh",
                "WOL-E": "scripts/WOL-E.sh",
                "WPScan": "scripts/WPScan.sh",
                "WebScarab": "scripts/WebScarab.sh",
                "WebSploit": "scripts/WebSploit.sh",
                "Webshag": "scripts/Webshag.sh",
                "Webshells": "scripts/Webshells.sh",
                "Weevely": "scripts/Weevely.sh",
                "Wfuzz": "scripts/Wfuzz.sh",
                "Wifi Honey": "scripts/Wifi_Honey.sh",
                "Wifitap": "scripts/Wifitap.sh",
                "Wifite": "scripts/Wifite.sh",
                "Winexe": "scripts/Winexe.sh",
                "Wireshark": "scripts/Wireshark.sh",
                "XSSer": "scripts/XSSer.sh",
                "Xplico": "scripts/Xplico.sh",
                "YARA": "scripts/YARA.sh",
                "Yersinia": "scripts/Yersinia.sh",
                "acccheck": "scripts/acccheck.sh",
                "ace-voip": "scripts/ace-voip.sh",
                "apache-users": "scripts/apache-users.sh",
                "apktool": "scripts/apktool.sh",
                "braa": "scripts/braa.sh",
                "bulk-extractor": "scripts/bulk-extractor.sh",
                "chntpw": "scripts/chntpw.sh",
                "cisco-auditing-tool": "scripts/cisco-auditing-tool.sh",
                "cisco-global-exploiter": "scripts/cisco-global-exploiter.sh",
                "cisco-ocs": "scripts/cisco-ocs.sh",
                "cisco-torch": "scripts/cisco-torch.sh",
                "coWPAtty": "scripts/coWPAtty.sh",
                "copy-router-config": "scripts/copy-router-config.sh",
                "crackle": "scripts/crackle.sh",
                "creddump": "scripts/creddump.sh",
                "crunch": "scripts/crunch.sh",
                "dbd": "scripts/dbd.sh",
                "dc3dd": "scripts/dc3dd.sh",
                "ddrescue": "scripts/ddrescue.sh",
                "deblaze": "scripts/deblaze.sh",
                "dex2jar": "scripts/dex2jar.sh",
                "dnmap": "scripts/dnmap.sh",
                "dns2tcp": "scripts/dns2tcp.sh",
                "dnsenum": "scripts/dnsenum.sh",
                "dnsmap": "scripts/dnsmap.sh",
                "dnstracer": "scripts/dnstracer.sh",
                "dnswalk": "scripts/dnswalk.sh",
                "dos2unix": "scripts/dos2unix.sh",
                "eapmd5pass": "scripts/eapmd5pass.sh",
                "edb-debugger": "scripts/edb-debugger.sh",
                "enum4linux": "scripts/enum4linux.sh",
                "enumIAX": "scripts/enumIAX.sh",
                "exploitdb": "scripts/exploitdb.sh",
                "extundelete": "scripts/extundelete.sh",
                "fiked": "scripts/fiked.sh",
                "fimap": "scripts/fimap.sh",
                "findmyhash": "scripts/findmyhash.sh",
                "fragroute": "scripts/fragroute.sh",
                "fragrouter": "scripts/fragrouter.sh",
                "goofile": "scripts/goofile.sh",
                "gpp-decrypt": "scripts/gpp-decrypt.sh",
                "hamster-sidejack": "scripts/hamster-sidejack.sh",
                "hash-identifier": "scripts/hash-identifier.sh",
                "hping3": "scripts/hping3.sh",
                "http-tunnel": "scripts/http-tunnel.sh",
                "iPhone Backup Analyzer": "scripts/iPhone_Backup_Analyzer.sh",
                "iSMTP": "scripts/iSMTP.sh",
                "iaxflood": "scripts/iaxflood.sh",
                "inviteflood": "scripts/inviteflood.sh",
                "ipv6-toolkit": "scripts/ipv6-toolkit.sh",
                "jSQL": "scripts/jSQL.sh",
                "jad": "scripts/jad.sh",
                "javasnoop": "scripts/javasnoop.sh",
                "jboss-autopwn": "scripts/jboss-autopwn.sh",
                "joomscan": "scripts/joomscan.sh",
                "kalibrate-rtl": "scripts/kalibrate-rtl.sh",
                "keimpx": "scripts/keimpx.sh",
                "lbd": "scripts/lbd.sh",
                "masscan": "scripts/masscan.sh",
                "mdk3": "scripts/mdk3.sh",
                "mfcuk": "scripts/mfcuk.sh",
                "mfoc": "scripts/mfoc.sh",
                "mfterm": "scripts/mfterm.sh",
                "mitmproxy": "scripts/mitmproxy.sh",
                "multiforcer": "scripts/multiforcer.sh",
                "ntop": "scripts/ntop.sh",
                "ohrwurm": "scripts/ohrwurm.sh",
                "openvas-cli": "scripts/openvas-cli.sh",
                "openvas-manager": "scripts/openvas-manager.sh",
                "openvas-scanner": "scripts/openvas-scanner.sh",
                "p0f": "scripts/p0f.sh",
                "patator": "scripts/patator.sh",
                "pdf-parser": "scripts/pdf-parser.sh",
                "pdfid": "scripts/pdfid.sh",
                "pdgmail": "scripts/pdgmail.sh",
                "peepdf": "scripts/peepdf.sh",
                "phrasendrescher": "scripts/phrasendrescher.sh",
                "pipal": "scripts/pipal.sh",
                "plecost": "scripts/plecost.sh",
                "polenum": "scripts/polenum.sh",
                "protos-sip": "scripts/protos-sip.sh",
                "pwnat": "scripts/pwnat.sh",
                "rcracki-mt": "scripts/rcracki-mt.sh",
                "rebind": "scripts/rebind.sh",
                "redfang": "scripts/redfang.sh",
                "responder": "scripts/responder.sh",
                "rtpbreak": "scripts/rtpbreak.sh",
                "rtpflood": "scripts/rtpflood.sh",
                "rtpinsertsound": "scripts/rtpinsertsound.sh",
                "rtpmixsound": "scripts/rtpmixsound.sh",
                "sbd": "scripts/sbd.sh",
                "sctpscan": "scripts/sctpscan.sh",
                "sfuzz": "scripts/sfuzz.sh",
                "smali": "scripts/smali.sh",
                "smtp-user-enum": "scripts/smtp-user-enum.sh",
                "snmpcheck": "scripts/snmpcheck.sh",
                "sqlmap": "scripts/sqlmap.sh",
                "sqlsus": "scripts/sqlsus.sh",
                "sslcaudit": "scripts/sslcaudit.sh",
                "sslstrip": "scripts/sslstrip.sh",
                "t50": "scripts/t50.sh",
                "theHarvester": "scripts/theHarvester.sh",
                "tnscmd10g": "scripts/tnscmd10g.sh",
                "twofi": "scripts/twofi.sh",
                "ua-tester": "scripts/ua-tester.sh",
                "unix-privesc-check": "scripts/unix-privesc-check.sh",
                "w3af": "scripts/w3af.sh",
                "wordlists": "scripts/wordlists.sh",
                "xspy": "scripts/xspy.sh",
                "zaproxy": "scripts/zaproxy.sh"}

info = {"1": "acccheck", "2": "ace-voip", "3": "Amap", "4": "Automater",
        "5": "braa", "6": "CaseFile", "7": "CDPSnarf", "8": "cisco-torch",
        "9": "CookieCadger", "10": "copy-router-config", "11": "DMitry",
        "12": "dnmap", "13": "dnsenum", "14": "dnsmap", "15": "DNSRecon",
        "16": "dnstracer", "17": "dnswalk", "18": "DotDotPwn",
        "19": "enum4linux", "20": "enumIAX", "21": "exploitdb",
        "22": "Fierce", "23": "Firewalk", "24": "fragroute",
        "25": "fragrouter", "26": "GhostPhisher", "27": "GoLismero",
        "28": "goofile", "29": "hping3", "30": "InTrace", "31": "iSMTP",
        "32": "lbd", "33": "MaltegoTeeth", "34": "masscan",
        "35": "Metagoofil", "36": "Miranda", "37": "Nmap", "38": "ntop",
        "39": "p0f", "40": "Parsero", "41": "Recon-ng", "42": "SET",
        "43": "smtp-user-enum", "44": "snmpcheck", "45": "sslcaudit",
        "46": "SSLsplit", "47": "sslstrip", "48": "SSLyze", "49": "THC-IPV6",
        "50": "theHarvester", "51": "TLSSLed", "52": "twofi", "53": "URLCrazy",
        "54": "Wireshark", "55": "WOL-E", "56": "Xplico"}

vulnerability = {"1": "BBQSQL", "2": "BED", "3": "cisco-auditing-tool",
                 "4": "cisco-global-exploiter", "5": "cisco-ocs",
                 "6": "cisco-torch", "7": "copy-router-config",
                 "8": "DBPwAudit", "9": "Doona", "10": "DotDotPwn",
                 "11": "GreenboneSecurityAssistant", "12": "HexorBase",
                 "13": "Inguma", "14": "jSQL", "15": "Lynis", "16": "Nmap",
                 "17": "ohrwurm", "18": "openvas-cli", "19": "openvas-manager",
                 "20": "openvas-scanner", "21": "Oscanner",
                 "22": "Powerfuzzer", "23": "sfuzz", "24": "SidGuesser",
                 "25": "SIPArmyKnife", "26": "sqlmap", "27": "Sqlninja",
                 "28": "sqlsus", "29": "THC-IPV6", "30": "tnscmd10g",
                 "31": "unix-privesc-check", "32": "Yersinia"}

wifi = {"1": "Aircrack-ng", "2": "Asleap", "3": "Bluelog", "4": "BlueRanger",
        "5": "Bluesnarfer", "6": "Bully", "7": "coWPAtty", "8": "crackle",
        "9": "eapmd5pass", "10": "FernWifiCracker", "11": "GhostPhisher",
        "12": "GISKismet", "13": "Gqrx", "14": "kalibrate-rtl",
        "15": "KillerBee", "16": "Kismet", "17": "mdk3", "18": "mfcuk",
        "19": "mfoc", "20": "mfterm", "21": "Multimon-NG", "22": "PixieWPS",
        "23": "Reaver", "24": "redfang", "25": "RTLSDRScanner",
        "26": "Spooftooph", "27": "WifiHoney", "28": "Wifitap", "29": "Wifite"}

sniff_n_spoof = {"1": "BurpSuite", "2": "DNSChef", "3": "fiked",
                 "4": "hamster-sidejack", "5": "HexInject", "6": "iaxflood",
                 "7": "inviteflood", "8": "iSMTP", "9": "mitmproxy",
                 "10": "ohrwurm", "11": "protos-sip", "12": "rebind",
                 "13": "responder", "14": "rtpbreak", "15": "rtpinsertsound",
                 "16": "rtpmixsound", "17": "sctpscan", "18": "SIPArmyKnife",
                 "19": "SIPp", "20": "SIPVicious", "21": "SSLsplit",
                 "22": "sslstrip", "23": "THC-IPV6", "24": "VoIPHopper",
                 "25": "WebScarab", "26": "WifiHoney", "27": "Wireshark",
                 "28": "xspy", "29": "Yersinia", "30": "zaproxy"}

access = {"1": "CryptCat", "2": "Cymothoa", "3": "dbd", "4": "dns2tcp",
          "5": "http-tunnel", "6": "HTTPTunnel", "7": "Intersect",
          "8": "Nishang", "9": "polenum", "10": "PowerSploit",
          "11": "pwnat", "12": "RidEnum", "13": "sbd", "14": "U3-Pwn",
          "15": "Webshells", "16": "Weevely", "17": "Winexe"}

report = {"1": "CaseFile", "2": "CutyCapt", "3": "dos2unix", "4": "Dradis",
          "5": "KeepNote", "6": "MagicTree", "7": "Metagoofil",
          "8": "Nipper-ng", "9": "pipal"}

exploit = {"1": "Armitage", "2": "BackdoorFactory", "3": "BeEF",
           "4": "cisco-auditing-tool", "5": "cisco-global-exploiter",
           "6": "cisco-ocs", "7": "cisco-torch", "8": "Commix", "9": "crackle",
           "10": "jboss-autopwn", "11": "LinuxExploitSuggester",
           "12": "MaltegoTeeth", "13": "SET", "14": "ShellNoob",
           "15": "sqlmap", "16": "THC-IPV6", "17": "Yersinia"}

forensics = {"1": "Binwalk", "2": "bulk-extractor", "3": "chntpw",
             "4": "Cuckoo", "5": "dc3dd", "6": "ddrescue", "7": "Dumpzilla",
             "8": "extundelete", "9": "Foremost", "10": "Galleta",
             "11": "Guymager", "12": "iPhoneBackupAnalyzer", "13": "p0f",
             "14": "pdf-parser", "15": "pdfid", "16": "pdgmail",
             "17": "peepdf", "18": "Volatility", "19": "Xplico"}

stress_test = {"1": "DHCPig", "2": "FunkLoad", "3": "iaxflood",
               "4": "inviteflood", "5": "ipv6-toolkit", "6": "mdk3",
               "7": "Reaver", "8": "rtpflood", "9": "SlowHTTPTest",
               "10": "t50", "11": "Termineter", "12": "THC-IPV6",
               "13": "THC-SSL-DOS"}

password = {"1": "acccheck", "2": "BurpSuite", "3": "CeWL", "4": "chntpw",
            "5": "cisco-auditing-tool", "6": "CmosPwd", "7": "creddump",
            "8": "crunch", "9": "DBPwAudit", "10": "findmyhash",
            "11": "gpp-decrypt", "12": "hash-identifier", "13": "HexorBase",
            "14": "THC-Hydra", "15": "JohntheRipper", "16": "Johnny",
            "17": "keimpx", "18": "MaltegoTeeth", "19": "Maskprocessor",
            "20": "multiforcer", "21": "Ncrack", "22": "PACK", "23": "patator",
            "24": "phrasendrescher", "25": "polenum", "26": "RainbowCrack",
            "27": "rcracki-mt", "28": "RSMangler", "29": "Statsprocessor",
            "30": "THC-pptp-bruter", "31": "TrueCrack", "32": "WebScarab",
            "33": "wordlists", "34": "zaproxy"}

rev_engineer = {"1": "apktool", "2": "dex2jar", "3": "edb-debugger",
                "4": "jad", "5": "javasnoop", "6": "smali",
                "7": "Valgrind", "8": "YARA"}

hw_hacking = {"1": "apktool", "2": "Arduino", "3": "dex2jar",
              "4": "Sakis3G", "5": "smali"}

webapps = {"1": "apache-users", "2": "Arachni", "3": "BBQSQL",
           "4": "BlindElephant", "5": "BurpSuite", "6": "CutyCapt",
           "7": "DAVTest", "8": "deblaze", "9": "DIRB", "10": "DirBuster",
           "11": "fimap", "12": "FunkLoad", "13": "Grabber",
           "14": "jboss-autopwn", "15": "joomscan", "16": "jSQL",
           "17": "MaltegoTeeth", "18": "PadBuster", "19": "Paros",
           "20": "Parsero", "21": "plecost", "22": "Powerfuzzer",
           "23": "ProxyStrike", "24": "Recon-ng", "25": "Skipfish",
           "26": "sqlmap", "27": "Sqlninja", "28": "sqlsus", "29": "ua-tester",
           "30": "Uniscan", "31": "Vega", "32": "w3af", "33": "WebScarab",
           "34": "Webshag", "35": "WebSploit", "36": "Wfuzz", "37": "WPScan",
           "38": "XSSer", "39": "zaproxy"}

categories = [info, vulnerability, wifi, sniff_n_spoof, access, report,
              exploit, forensics, stress_test, password, rev_engineer,
              hw_hacking, webapps]
